- name: Playbook
  hosts: webservers
  become: yes
  become_user: root
  tasks:
      - name: install nginx
        yum:
          name: nginx
          state: present
      - name: ensure nginx is running
        service:
          name: nginx
          state: started
      - name: Insert Index Page
        template:
         src: index.html
         dest: /usr/share/nginx/html/index.html
